### ISSUE TITLE
-audioquality -1 quality is not highes (-aq -1 and -aq 0 output is the same)

### ISSUE THREAD

**Issue by aatv** [jmf1988/ytdash#2]
With -aq -1 stream should have higher 48000Hz webm audio quality (vs medium audio quality of 44100Hz with -aq 1)

More details:

Source Live Video stream have this audio codec options:
> 249          webm       audio only tiny   62k , opus @ 50k (48000Hz), 60.80MiB
> 250          webm       audio only tiny   79k , opus @ 70k (48000Hz), 79.54MiB
> 140          m4a        audio only tiny  140k , m4a_dash container, mp4a.40.2@128k (44100Hz)
> 251          webm       audio only tiny  143k , opus @ 160k (48000Hz), 155.83MiB

I have tried to change audio quality in ytdash using this switch:

> -audioquality {0,1,-1}, -aq {0,1,-1}
> Audio quality to enable if available, 0=lowest, 1=medium, -1=highest. (default: 1)

Both -aq 1 and -aq -1 settings produce the same 44100Hz (m4a) audio output.

**Comment by jmf1988** [comment]
For now ytdash only supports MP4 container format, so audio inside webm is filtered out, however I can see if is possible to add only the audio source from there.

**Comment by jmf1988** [comment]
All live streams I tested had only mp4a/aac audio available (with either avc1/h264 or vp9), but, I saw opus available in almost all non live streams, so now I added support for it to ytdash in last update for those videos (non protected, non restricted public videos only), -audioquality is defaulting to -1  so the highest quality is selected by bitrate automatically, but a codec can be priorized over the other with a flag. 
So, or the stream wasn't live or it ended between tries so opus source became available.
